CREATE ROLE mv_app_runtime LOGIN PASSWORD 'CHANGE_ME';

GRANT CONNECT ON DATABASE postgres TO mv_app_runtime;
GRANT USAGE ON SCHEMA public TO mv_app_runtime;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO mv_app_runtime;
GRANT USAGE, SELECT, UPDATE ON ALL SEQUENCES IN SCHEMA public TO mv_app_runtime;

ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO mv_app_runtime;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT USAGE, SELECT, UPDATE ON SEQUENCES TO mv_app_runtime;
