# Generated by Django 5.2.8 on 2026-01-20 14:16

import userauths.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0027_deliverycouriers_url_parameter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.FileField(blank=True, default='product.jpg', max_length=500, null=True, upload_to=userauths.models.user_directory_path),
        ),
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
