# Generated by Django 5.2.8 on 2026-01-21 06:25

import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0028_alter_product_brand_alter_product_image_and_more'),
        ('vendor', '0003_alter_vendor_description'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='cart',
            index=models.Index(fields=['cart_id'], name='store_cart_cartid_idx'),
        ),
        migrations.AddIndex(
            model_name='cart',
            index=models.Index(fields=['cart_id', 'user'], name='store_cart_cartid_user_idx'),
        ),
        migrations.AddIndex(
            model_name='cart',
            index=models.Index(fields=['user'], name='store_cart_user_idx'),
        ),
        migrations.AddIndex(
            model_name='cart',
            index=models.Index(fields=['product'], name='store_cart_product_idx'),
        ),
        migrations.AddIndex(
            model_name='cartorder',
            index=models.Index(fields=['oid'], name='store_order_oid_idx'),
        ),
        migrations.AddIndex(
            model_name='cartorder',
            index=models.Index(fields=['stripe_session_id'], name='store_order_stripe_session_idx'),
        ),
        migrations.AddIndex(
            model_name='cartorder',
            index=models.Index(fields=['payment_status'], name='store_order_payment_status_idx'),
        ),
        migrations.AddIndex(
            model_name='cartorder',
            index=models.Index(fields=['order_status'], name='store_order_order_status_idx'),
        ),
        migrations.AddIndex(
            model_name='cartorder',
            index=models.Index(fields=['buyer'], name='store_order_buyer_idx'),
        ),
        migrations.AddIndex(
            model_name='cartorder',
            index=models.Index(fields=['date'], name='store_order_date_idx'),
        ),
        migrations.AddIndex(
            model_name='cartorder',
            index=models.Index(fields=['payment_status', 'date'], name='store_order_payment_date_idx'),
        ),
        migrations.AddIndex(
            model_name='cartorderitem',
            index=models.Index(fields=['oid'], name='store_orderitem_oid_idx'),
        ),
        migrations.AddIndex(
            model_name='cartorderitem',
            index=models.Index(fields=['vendor'], name='store_orderitem_vendor_idx'),
        ),
        migrations.AddIndex(
            model_name='cartorderitem',
            index=models.Index(fields=['vendor', 'date'], name='st_oit_v_date_idx'),
        ),
        migrations.AddIndex(
            model_name='cartorderitem',
            index=models.Index(fields=['order'], name='store_orderitem_order_idx'),
        ),
        migrations.AddIndex(
            model_name='cartorderitem',
            index=models.Index(fields=['order', 'vendor'], name='st_oit_o_v_idx'),
        ),
        migrations.AddIndex(
            model_name='cartorderitem',
            index=models.Index(fields=['product'], name='store_orderitem_product_idx'),
        ),
        migrations.AddIndex(
            model_name='cartorderitem',
            index=models.Index(fields=['delivery_status'], name='st_oit_del_stat_idx'),
        ),
        migrations.AddIndex(
            model_name='cartorderitem',
            index=models.Index(fields=['date'], name='store_orderitem_date_idx'),
        ),
        migrations.AddIndex(
            model_name='coupon',
            index=models.Index(fields=['vendor', 'active'], name='store_coupon_vendor_active_idx'),
        ),
        migrations.AddIndex(
            model_name='coupon',
            index=models.Index(fields=['active'], name='store_coupon_active_idx'),
        ),
        migrations.AddIndex(
            model_name='coupon',
            index=models.Index(fields=['cid'], name='store_coupon_cid_idx'),
        ),
        migrations.AddIndex(
            model_name='coupon',
            index=models.Index(django.db.models.functions.text.Lower('code'), name='store_coupon_code_lower_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['vendor', 'seen'], name='store_noti_vendor_seen_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', 'seen'], name='store_noti_user_seen_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['date'], name='store_noti_date_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['slug'], name='store_product_slug_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['status'], name='store_product_status_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['vendor'], name='store_product_vendor_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['vendor', 'status'], name='st_prod_v_stat_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['status', 'featured'], name='st_prod_stat_feat_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['status', 'hot_deal'], name='st_prod_stat_hot_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['status', 'special_offer'], name='st_prod_stat_offer_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['status', 'type'], name='store_product_status_type_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['date'], name='store_product_date_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['product'], name='store_review_product_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['active'], name='store_review_active_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['product', 'active'], name='st_rev_prod_act_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['date'], name='store_review_date_idx'),
        ),
    ]
