# Generated by Cascade on 2026-01-21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0029_cart_store_cart_cartid_idx_and_more"),
    ]

    operations = [
        migrations.RunSQL(
            sql="CREATE EXTENSION IF NOT EXISTS pg_trgm;",
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RunSQL(
            sql=(
                "CREATE INDEX IF NOT EXISTS st_prod_title_trgm_gin "
                "ON store_product USING gin (title gin_trgm_ops);"
            ),
            reverse_sql="DROP INDEX IF EXISTS st_prod_title_trgm_gin;",
        ),
    ]
